# Use the official Ubuntu image as a base
# FROM ubuntu:latest
FROM ubuntu:18.04

# Update the package list and install basic packages
RUN apt-get update && apt-get install -y vim curl wget git

WORKDIR /AutoDef

### install Anaconda
RUN mkdir deps/
RUN wget -O deps/anaconda.sh https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh
RUN bash deps/anaconda.sh -b -p ./extern/anaconda

# Other Deps
RUN apt-get install build-essential curl git cmake unzip autoconf autogen automake libtool mlocate zlib1g-dev g++-7 python python3-numpy python3-dev python3-pip python3-wheel wget libboost-all-dev pkg-config zip g++ zlib1g-dev unzip python -y
RUN updatedb


### For tensorflow cc
# Bazel
RUN wget -O deps/bazel.sh https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-installer-linux-x86_64.sh
RUN bash deps/bazel.sh

ADD . .

# # build and install my version of tensorflow
# WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc
# RUN mkdir build
# WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc/build
# RUN cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
# RUN make -j8 && sudo make install; exit 0
# WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc/build/tensorflow
# RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./pip_package_build
# WORKDIR /AutoDef
# RUN extern/anaconda/bin/pip install --upgrade extern/tensorflow_cc/tensorflow_cc/build/tensorflow/pip_package_build/tensorflow-1.8.0-cp36-cp36m-linux_x86_64.whl


RUN rm -rf extern/tensorflow_cc/
WORKDIR /AutoDef/extern
RUN git clone https://github.com/ericchen321/tensorflow_cc.git
WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc
RUN mkdir build
WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc/build
RUN cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON -DALLOW_CUDA=OFF ..
RUN make -j8 -k 2>&1 | tee build.log
RUN make install
WORKDIR /AutoDef/extern/tensorflow_cc/tensorflow_cc/build/tensorflow
RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./pip_package_build
WORKDIR /AutoDef
# RUN extern/anaconda/bin/pip install --upgrade pip
# RUN extern/anaconda/bin/pip install --upgrade pip
# RUN extern/anaconda/bin/pip install protobuf==3.4.0
# RUN extern/anaconda/bin/pip install extern/tensorflow_cc/tensorflow_cc/build/tensorflow/pip_package_build/tensorflow-1.8.0-cp36-cp36m-linux_x86_64.whl





# Set the default command to run when the container starts
CMD ["bash"]