
FROM nvidia/cudagl:11.4.2-devel-ubuntu18.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    libgl1-mesa-dev \
    libglew-dev \
    libglfw3-dev \
    libx11-dev \
    libxrandr-dev \
    libxi-dev \
    libxxf86vm-dev \
    libxcursor-dev \
    libxinerama-dev \
    && rm -rf /var/lib/apt/lists/*

# Update the package list and install basic packages
RUN apt-get update && apt-get install -y vim curl wget git

WORKDIR /AutoDef

### install Anaconda
RUN mkdir deps/
RUN wget -O deps/anaconda.sh https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh
RUN bash deps/anaconda.sh -b -p ./extern/anaconda

# Other Deps
RUN apt-get install build-essential curl git cmake unzip autoconf autogen automake libtool mlocate zlib1g-dev g++-7 python python3-numpy python3-dev python3-pip python3-wheel wget libboost-all-dev pkg-config zip g++ zlib1g-dev unzip python -y
RUN updatedb


### For tensorflow cc
# Bazel
RUN wget -O deps/bazel.sh https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-installer-linux-x86_64.sh
RUN bash deps/bazel.sh

ADD . .

